mqtt_server: mosquitto
mqtt_port: 1883
mqtt_username: user
mqtt_password: pass
mqtt_topic: sungrowmodbus2mqtt/

ha_device_id: sungrow_sh20t
ha_device_name: Sungrow SH20T

ip: 192.168.0.55 # ip of Sungrow LAN-Port
slave_id: 0x1

update_rate: 2 # pull rate in seconds
address_offset: -1
scan_batching: 120
word_order: little
logging: info

holding:
  - pub_topic: start_stop
    address: 13000
    retain: true
    value_map:
      0xcf: start
      0xce: stop
  - pub_topic: do_configuration
    address: 13001
    retain: true
    value_map:
      0x0: "off"
      0x1: load_control_mode
      0x2: grounding_fault_indication
      0x3: microgrid_system_mode
  - pub_topic: load_control_mode
    address: 13002
    retain: true
    value_map:
      0x0: timing
      0x1: on_off
      0x2: power_optimized
      0x3: disable
  - pub_topic: ems_mode
    address: 13050
    retain: true
    value_map:
      0x0: self-consumption
      0x2: forced
      0x3: external_ems
      0x4: vpp
  - pub_topic: charge_discharge
    address: 13051
    retain: true
    value_map:
      0xaa: charge
      0xbb: discharge
      0xcc: stop
  - pub_topic: charge_discharge_power
    address: 13052
    retain: true
    unit: "W"
  - pub_topic: max_soc
    address: 13058
    retain: true
    scale: 0.1
    unit: "%"
  - pub_topic: min_soc
    address: 13059
    retain: true
    scale: 0.1
    unit: "%"
  - pub_topic: export_power_limitation_value
    address: 13074
    retain: true
    unit: "W"
  - pub_topic: meter_comm_detection
    address: 13086
    retain: true
    value_map:
      0xaa: enable
      0x55: disable
  - pub_topic: export_power_limitation
    address: 13087
    retain: true
    value_map:
      0xaa: enable
      0x55: disable
  - pub_topic: reserved_soc_for_backup
    address: 13100
    retain: true
    unit: "%"

input:
  - pub_topic: device_type_code
    address: 5000
    retain: true
    value_map:
      0xd17: sh3.0rs
      0xd0d: sh3.6rs
      0xd18: sh4.0rs
      0xd0f: sh5.0rs
      0xd10: sh6.0rs
      0xd1a: sh8.0rs
      0xd1b: sh10rs
      0xe00: sh5.0rt
      0xe01: sh6.0rt
      0xe02: sh8.0rt
      0xe03: sh10rt
      0xe10: sh5.0rt-20
      0xe11: sh6.0rt-20
      0xe12: sh8.0rt-20
      0xe13: sh10rt-20
      0xe0c: sh5.0rt-v112
      0xe0d: sh6.0rt-v112
      0xe0e: sh8.0rt-v112
      0xe0f: sh10rt-v112
      0xe08: sh5.0rt-v122
      0xe09: sh6.0rt-v122
      0xe0a: sh8.0rt-v122
      0xe0b: sh10rt-v122
      0xe20: sh5t-v11
      0xe21: sh6t-v11
      0xe22: sh8t-v11
      0xe23: sh10t-v11
      0xe24: sh12t-v11
      0xe25: sh15t-v11
      0xe26: sh20t-v11
      0xe28: sh25t-v11

      0xd03: sh5k-v13
      0xd06: sh3k6
      0xd07: sh4k6
      0xd09: sh5k-20
      0xd0a: sh3k6-30
      0xd0b: sh4k6-30
      0xd0c: sh5k-30
      0xd0e: sh4.6rs
  - pub_topic: nominal_output_power
    address: 5001
    retain: true
    scale: 0.1
    unit: "kW"
  - pub_topic: output_type
    address: 5002
    retain: true
    value_map:
      0x0: single
      0x1: 3p4l
      0x2: 3p3l
  - pub_topic: daily_output_energy
    address: 5003
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_output_energy
    type: uint32
    address: 5004
    scale: 0.1
    unit: "kWh"
  - pub_topic: inside_temperature
    type: int16
    address: 5008
    scale: 0.1
    unit: "°C"
  - pub_topic: mppt1_voltage
    address: 5011
    scale: 0.1
    unit: "V"
  - pub_topic: mppt1_current
    address: 5012
    scale: 0.1
    unit: "A"
  - pub_topic: mppt2_voltage
    address: 5013
    scale: 0.1
    unit: "V"
  - pub_topic: mppt2_current
    address: 5014
    scale: 0.1
    unit: "A"
  - pub_topic: mppt3_voltage
    address: 5015
    scale: 0.1
    unit: "V"
  - pub_topic: mppt3_current
    address: 5016
    scale: 0.1
    unit: "A"
  - pub_topic: total_dc_power
    type: uint32
    address: 5017
    unit: "W"
  - pub_topic: phase_a_voltage
    address: 5019
    scale: 0.1
    unit: "V"
  - pub_topic: phase_b_voltage
    address: 5020
    scale: 0.1
    unit: "V"
  - pub_topic: phase_c_voltage
    address: 5021
    scale: 0.1
    unit: "V"
  - pub_topic: reactive_power
    type: int32
    address: 5033
  - pub_topic: power_factor
    type: int16
    address: 5035
    scale: 0.001
#  - pub_topic: grid_frequency
#    address: 5036
#    scale: 0.1
#    unit: "Hz"
  - pub_topic: battery_power
    type: int32
    address: 5214
    unit: "W"
  - pub_topic: grid_frequency
    address: 5242
    scale: 0.01
    unit: "Hz"
  - pub_topic: battery_current
    type: int16
    address: 5631
    scale: 0.1
    unit: "A"
  - pub_topic: running_state
    address: 13000
    value_map:
      0x0: running
      0x1: stop
      0x2: shutdown
      0x4: emergency_stop
      0x8: standby
      0x10: initial_standby
      0x20: startup
      0x40: running
      0x41: off-grid_charge
      0x100: fault
      0x200: update_failed
      0x400: running_in_maintain_mode
      0x800: running_in_forced_mode
      0x1000: running_in_off-grid_mode
      0x1111: uninitialized
      0x1300: shutdown
      0x1400: standby
      0x1500: emergency_stop
      0x1600: startup
      0x1700: afci_self-test_shutdown
      0x1800: intelligent_station_building_status
      0x1900: safe_mode
      0x2000: open_loop
      0x2501: restarting
      0x4000: running_in_external_ems_mode
      0x4001: emergency_charging_operation
      0x8000: stop
      0x8100: derating_running
      0x8200: dispatch_running
      0x9100: warn_run
      0x12000: initial_standby
      0x55000: fault
  - pub_topic: power_flow_status
    address: 13001
  - pub_topic: power_flow_status_pv_power
    address: 13001
    mask: 0x1
    sensor_type: "binary"
  - pub_topic: power_flow_status_battery_charging
    address: 13001
    mask: 0x2
    shift: 1
    sensor_type: "binary"
  - pub_topic: power_flow_status_battery_discharging
    address: 13001
    mask: 0x4
    shift: 2
    sensor_type: "binary"
  - pub_topic: power_flow_status_positive_load_power
    address: 13001
    mask: 0x8
    shift: 3
    sensor_type: "binary"
  - pub_topic: power_flow_status_feed_in_power
    address: 13001
    mask: 0x10
    shift: 4
    sensor_type: "binary"
  - pub_topic: power_flow_status_import_power_from_grid
    address: 13001
    mask: 0x20
    shift: 5
    sensor_type: "binary"
  - pub_topic: power_flow_status_negative_load_power
    address: 13001
    mask: 0x80
    shift: 7
    sensor_type: "binary"
  - pub_topic: daily_pv_generation
    address: 13002
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_pv_generation
    type: uint32
    address: 13003
    scale: 0.1
    unit: "kWh"
    sensor_type: measurement
  - pub_topic: daily_export_power_from_pv
    address: 13005
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_export_energy_from_pv
    type: uint32
    address: 13006
    scale: 0.1
    unit: "kWh"
  - pub_topic: load_power
    type: int32
    address: 13008
    unit: "W"
  - pub_topic: export_power
    type: int32
    address: 13010
    unit: "W"
  - pub_topic: daily_battery_charge_energy_from_pv
    address: 13012
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_battery_charge_energy_from_pv
    type: uint32
    address: 13013
    scale: 0.1
    unit: "kWh"
  - pub_topic: daily_direct_energy_consumption
    address: 13017
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_direct_energy_consumption
    type: uint32
    address: 13018
    scale: 0.1
    unit: "kWh"
  - pub_topic: battery_voltage
    address: 13020
    scale: 0.1
    unit: "V"
#  - pub_topic: battery_current
#    address: 13021
#    scale: 0.1
#    unit: "A"
#  - pub_topic: battery_power
#    address: 13022
#    unit: "W"
  - pub_topic: battery_level
    address: 13023
    scale: 0.1
    unit: "%"
    class: "battery"
  - pub_topic: battery_state_of_health
    address: 13024
    scale: 0.1
    unit: "%"
  - pub_topic: battery_temperature
    type: int16
    address: 13025
    scale: 0.1
    unit: "°C"
  - pub_topic: daily_battery_discharge_energy
    address: 13026
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_battery_discharge_energy
    type: uint32
    address: 13027
    scale: 0.1
    unit: "kWh"
    sensor_type: measurement
  - pub_topic: self_consumption_of_today
    address: 13029
    scale: 0.1
    unit: "%"
  - pub_topic: phase_a_current
    type: int16
    address: 13031
    scale: 0.1
    unit: "A"
  - pub_topic: phase_b_current
    type: int16
    address: 13032
    scale: 0.1
    unit: "A"
  - pub_topic: phase_c_current
    type: int16
    address: 13033
    scale: 0.1
    unit: "A"
  - pub_topic: total_active_power
    type: int32
    address: 13034
    unit: "W"
  - pub_topic: daily_import_energy
    address: 13036
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_import_energy
    type: uint32
    address: 13037
    scale: 0.1
    unit: "kWh"
    sensor_type: measurement
  - pub_topic: battery_capacity
    address: 13039
    retain: true
    scale: 0.1
    unit: "kWh"
  - pub_topic: daily_charge_energy
    address: 13040
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_charge_energy
    type: uint32
    address: 13041
    scale: 0.1
    unit: "kWh"
    sensor_type: measurement
  - pub_topic: daily_export_energy
    address: 13045
    scale: 0.1
    unit: "kWh"
  - pub_topic: total_export_energy
    type: uint32
    address: 13046
    scale: 0.1
    unit: "kWh"
    sensor_type: measurement
